name: PlatformIO CI

on:
  pull_request:
    branches:
      - main
      - master
      - develop
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - main
      - master
      - develop
    paths-ignore:
      - "**/*.md"

jobs:
  platformio:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        example:
          - "examples/PCA9685/Servo/Servo.ino"
          - "examples/PCA9685/VibroPulse/VibroPulse.ino"
        boards: [ [ uno, esp32dev ] ]

    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/.cache
            ./.pio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/*.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio upgrade --dev
          pio pkg update --global

      - name: Build example
        run: |
          pio ci --lib="." --board=${{ join(matrix.boards, ' --board=') }}
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
